#!/bin/bash

# Mise à jour des dépôts et installation des paquets requis
sudo apt-get update && sudo apt-get install -y ca-certificates apt-transport-https

# Ajout du dépôt UniFi dans le fichier de sources
echo 'deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list

# Téléchargement de la clé de confiance du dépôt UniFi
sudo wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg

# Ajout de la clé MongoDB
wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -

# Ajout du dépôt MongoDB dans le fichier de sources
echo "deb [trusted=yes] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list

# Mise à jour des dépôts après l'ajout des nouveaux
sudo apt-get update

# Installation de UniFi
sudo apt-get install -y unifi
